language: python

python:
  - "3.9"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - apt-get install python-dev
  - apt-get install libjpeg-dev
  - apt-get install libjpeg8-dev
  - apt-get install libpng3
  - apt-get install libfreetype6-dev
  - ln -s /usr/lib/i386-linux-gnu/libfreetype.so /usr/lib
  - ln -s /usr/lib/i386-linux-gnu/libjpeg.so /usr/lib
  - ln -s /usr/lib/i386-linux-gnu/libz.so /usr/lib
  - pip install PIL  --allow-unverified PIL --allow-all-external
  - pip install Pillow

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"

notifications:
  email: false
