language: python

python:
  - "3.9"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - sudo apt-get install python3 python-dev python3-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev python-pip

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"

notifications:
  email: false
